name = "docs-isharkfly-com"
main = "docs/worker.js" # Path to your Worker script logic
compatibility_date = "2026-06-25"

[assets]
directory = "./.vitepress/dist"
binding = "ASSETS"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
